import argparse

from typing import List, Dict

import dotenv
import spotipy

from rymscraper import rymscraper, RymUrl
from spotipy.oauth2 import SpotifyOAuth


def get_args():
    parser = argparse.ArgumentParser(
        description='Create a Spotify playlist based on the top tracks of a given year')
    parser.add_argument('year', type=int, help='The year to get the top tracks from')
    parser.add_argument('--pages', type=int, default=1, help='The number of pages to scrape')
    return parser.parse_args()


def get_top_tracks(year: int, pages: int = 1) -> List[Dict]:
    url = RymUrl.RymUrl(year=year, kind="single", language='en')
    RymNetwork = rymscraper.RymNetwork()
    list_rows = RymNetwork.get_chart_infos(url, max_page=pages)

    return list_rows


def main():
    args = get_args()
    scope = "user-library-read,playlist-modify-private"
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))

    top_tracks = get_top_tracks(args.year, args.pages)
    spotify_uris = []

    for track in top_tracks:
        songs = track['Album'].split(' / ')

        for song in songs:
            res = sp.search(q=f'artist:{track["Artist"]} track:{song}', type='track')

            try:
                spotify_uris.append(res['tracks']['items'][0]['uri'])
            except IndexError:
                pass

    user = sp.current_user()
    res = sp.user_playlist_create(
        user=user['id'],
        name=f'Top Tracks of {args.year}',
        public=False,
        description=f'The top singles of {args.year} according to Rate Your Music; generated by https://github.com/OfcPeriwinkle/top-tracks')

    sp.user_playlist_add_tracks(
        user=user['id'],
        playlist_id=res['id'],
        tracks=spotify_uris)


if __name__ == '__main__':
    dotenv.load_dotenv()
    main()
